[package]
name = "s3wf2"
version = "0.3.0"
authors = ["YÅ« Kobayashi <kb10uy@kb10uy.org>"]
edition = "2018"

[features]
cli = ["clap", "ansi_term"]
foreign = ["libc"]
wasm = ["wasm-bindgen", "console_error_panic_hook", "wee_alloc", "serde", "serde_json"]

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "s3wf2-cli"
path = "src/s3wf2-cli/main.rs"
required-features = ["cli"]

# Profiles --------------------------------------------------------------------

[profile.release]
lto = true

[package.metadata.docs.rs]
features = ["cli", "foreign", "wasm"]

# Dependencies ----------------------------------------------------------------

[dependencies.regex]
version = "1.3"
features = ["std", "perf", "unicode-perl"]

[dependencies.lazy_static]
version = "1.4"

[dependencies.ansi_term]
version = "0.12"
optional = true

[dependencies.clap]
version = "2.33"
features = ["yaml"]
optional = true

[dependencies.libc]
version = "0.2"
optional = true

[dependencies.wasm-bindgen]
version = "0.2"
optional = true
features = ["serde-serialize"]

[dependencies.console_error_panic_hook]
version = "0.1"
optional = true

[dependencies.serde]
version = "1.0"
optional = true
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
optional = true

[dependencies.wee_alloc]
version = "0.4"
optional = true
